"""Add unique constraint on number

Revision ID: 70209ab66b58
Revises: 
Create Date: 2025-01-11 09:58:58.236478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70209ab66b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('PINcode', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.drop_table('farmerinfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmerinfo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('PINcode', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='farmerinfo_pkey')
    )
    op.drop_table('farmer_info')
    # ### end Alembic commands ###
